"""baseline

Revision ID: a4165976bce3
Revises: 0abb4e0eed48
Create Date: 2025-08-14 12:38:58.675159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4165976bce3'
down_revision = '0abb4e0eed48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('joined_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('left_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.drop_column('left_at')
        batch_op.drop_column('joined_at')
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
