"""link GradeHistory to ActivityOutsideRecord

Revision ID: 0abb4e0eed48
Revises: f175e4775bc4
Create Date: 2025-08-14 09:58:49.630687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0abb4e0eed48'
down_revision = 'f175e4775bc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grade_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activity_outside_record_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_grade_history_activity_outside_record_id',  # ★名前を付ける
            'activity_outside_record',
            ['activity_outside_record_id'],
            ['id']
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grade_history', schema=None) as batch_op:
        batch_op.drop_constraint('fk_grade_history_activity_outside_record_id', type_='foreignkey')
        batch_op.drop_column('activity_outside_record_id')

    # ### end Alembic commands ###
