"""init schema (squashed)

Revision ID: 7ab49dfc3ce0
Revises: 
Create Date: 2025-09-09 19:54:51.296072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ab49dfc3ce0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('club',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('admin_password_hash', sa.String(length=255), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('handicap_rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('club_id', sa.String(), nullable=False),
    sa.Column('grade_diff', sa.Integer(), nullable=False),
    sa.Column('handicap', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('club_id', 'grade_diff', name='uq_handicap_rule_club_grade_diff')
    )
    with op.batch_alter_table('handicap_rule', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_handicap_rule_club_id'), ['club_id'], unique=False)

    op.create_table('setting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('club_id', sa.String(length=32), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('club_id', 'key', name='uq_setting_club_key')
    )
    with op.batch_alter_table('setting', schema=None) as batch_op:
        batch_op.create_index('ix_setting_club_key', ['club_id', 'key'], unique=False)

    op.create_table('default_card_count',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('club_id', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['club_id'], ['club.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('club_id', name='uq_default_card_count_club')
    )
    with op.batch_alter_table('default_card_count', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_default_card_count_club_id'), ['club_id'], unique=False)

    op.create_table('match_card_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=20), nullable=False),
    sa.Column('card_index', sa.Integer(), nullable=False),
    sa.Column('match_type', sa.String(length=20), nullable=True),
    sa.Column('p1_id', sa.String(length=20), nullable=True),
    sa.Column('p2_id', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('info_html', sa.Text(), nullable=True),
    sa.Column('original_html1', sa.Text(), nullable=True),
    sa.Column('original_html2', sa.Text(), nullable=True),
    sa.Column('club_id', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['club_id'], ['club.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('match_card_state', schema=None) as batch_op:
        batch_op.create_index('ix_match_card_state_club_date_card', ['club_id', 'date', 'card_index'], unique=False)
        batch_op.create_index(batch_op.f('ix_match_card_state_club_id'), ['club_id'], unique=False)

    op.create_table('member',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('kana', sa.String(length=100), nullable=False),
    sa.Column('grade', sa.String(length=20), nullable=False),
    sa.Column('member_type', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('left_at', sa.DateTime(), nullable=True),
    sa.Column('qr_token', sa.String(length=32), nullable=True),
    sa.Column('club_id', sa.String(length=32), nullable=True),
    sa.Column('member_code', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['club_id'], ['club.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('club_id', 'member_code', name='uq_member_club_id_member_code')
    )
    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_member_club_id'), ['club_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_member_qr_token'), ['qr_token'], unique=True)

    op.create_table('owner_audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('club_id', sa.String(length=32), nullable=False),
    sa.Column('actor', sa.String(length=50), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['club.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('owner_audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_owner_audit_log_club_id'), ['club_id'], unique=False)

    op.create_table('promotion_rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_strength', sa.String(length=20), nullable=False),
    sa.Column('to_strength', sa.String(length=20), nullable=False),
    sa.Column('win_streak', sa.Integer(), nullable=True),
    sa.Column('win1', sa.Integer(), nullable=True),
    sa.Column('lose1', sa.Integer(), nullable=True),
    sa.Column('win2', sa.Integer(), nullable=True),
    sa.Column('lose2', sa.Integer(), nullable=True),
    sa.Column('club_id', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['club_id'], ['club.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('club_id', 'from_strength', 'to_strength', name='uq_promotion_rule_club_pair')
    )
    with op.batch_alter_table('promotion_rule', schema=None) as batch_op:
        batch_op.create_index('ix_promotion_rule_club', ['club_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_promotion_rule_club_id'), ['club_id'], unique=False)

    op.create_table('strength',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('club_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['club.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('club_id', 'name', name='uq_strength_club_name'),
    sa.UniqueConstraint('club_id', 'order', name='uq_strength_club_order')
    )
    with op.batch_alter_table('strength', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_strength_club_id'), ['club_id'], unique=False)

    op.create_table('today_participant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('kana', sa.String(), nullable=True),
    sa.Column('grade', sa.String(), nullable=True),
    sa.Column('member_type', sa.String(), nullable=True),
    sa.Column('club_id', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['club_id'], ['club.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('today_participant', schema=None) as batch_op:
        batch_op.create_index('ix_today_participant_club_date_pid', ['club_id', 'date', 'participant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_today_participant_club_id'), ['club_id'], unique=False)

    op.create_table('activity_outside_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.String(length=20), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=False),
    sa.Column('club_id', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['club_id'], ['club.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activity_outside_record', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_outside_record_club_id'), ['club_id'], unique=False)

    op.create_table('blind_count',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.String(length=20), nullable=False),
    sa.Column('counted_from', sa.DateTime(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=2), nullable=False),
    sa.Column('club_id', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['club_id'], ['club.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('blind_count', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blind_count_club_id'), ['club_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_blind_count_counted_from'), ['counted_from'], unique=False)
        batch_op.create_index(batch_op.f('ix_blind_count_member_id'), ['member_id'], unique=False)

    op.create_table('match',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player1_id', sa.String(length=20), nullable=False),
    sa.Column('player2_id', sa.String(length=20), nullable=False),
    sa.Column('match_type', sa.String(length=20), nullable=False),
    sa.Column('handicap', sa.String(length=50), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('is_recorded', sa.Boolean(), nullable=True),
    sa.Column('card_index', sa.Integer(), nullable=True),
    sa.Column('club_id', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['club_id'], ['club.id'], ),
    sa.ForeignKeyConstraint(['player1_id'], ['member.id'], ),
    sa.ForeignKeyConstraint(['player2_id'], ['member.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_match_club_id'), ['club_id'], unique=False)

    op.create_table('promotion_counter_reset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.String(length=20), nullable=False),
    sa.Column('reset_date', sa.DateTime(), nullable=False),
    sa.Column('club_id', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['club_id'], ['club.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('promotion_counter_reset', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_promotion_counter_reset_club_id'), ['club_id'], unique=False)

    op.create_table('grade_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.String(length=20), nullable=False),
    sa.Column('before_grade', sa.String(length=20), nullable=False),
    sa.Column('after_grade', sa.String(length=20), nullable=False),
    sa.Column('changed_at', sa.DateTime(), nullable=True),
    sa.Column('reason', sa.String(length=100), nullable=True),
    sa.Column('activity_outside_record_id', sa.Integer(), nullable=True),
    sa.Column('club_id', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['activity_outside_record_id'], ['activity_outside_record.id'], ),
    sa.ForeignKeyConstraint(['club_id'], ['club.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('grade_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_grade_history_club_id'), ['club_id'], unique=False)

    op.create_table('initial_assessment_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.String(length=20), nullable=False),
    sa.Column('assigned_grade', sa.String(length=20), nullable=False),
    sa.Column('evaluated_by', sa.String(length=50), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(), nullable=True),
    sa.Column('match_id', sa.Integer(), nullable=True),
    sa.Column('club_id', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['club_id'], ['club.id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['match.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('initial_assessment_result', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_initial_assessment_result_club_id'), ['club_id'], unique=False)

    op.create_table('match_memo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('club_id', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['club_id'], ['club.id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['match.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('match_memo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_match_memo_club_id'), ['club_id'], unique=False)

    op.create_table('match_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.String(length=20), nullable=False),
    sa.Column('result', sa.String(length=5), nullable=False),
    sa.Column('grade_at_time', sa.String(length=20), nullable=True),
    sa.Column('opponent_name', sa.String(length=50), nullable=True),
    sa.Column('opponent_grade', sa.String(length=20), nullable=True),
    sa.Column('post_grade', sa.String(length=20), nullable=True),
    sa.Column('promoted', sa.Boolean(), nullable=True),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('club_id', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['club_id'], ['club.id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['match.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['member.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('match_result', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_match_result_club_id'), ['club_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match_result', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_match_result_club_id'))

    op.drop_table('match_result')
    with op.batch_alter_table('match_memo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_match_memo_club_id'))

    op.drop_table('match_memo')
    with op.batch_alter_table('initial_assessment_result', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_initial_assessment_result_club_id'))

    op.drop_table('initial_assessment_result')
    with op.batch_alter_table('grade_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_grade_history_club_id'))

    op.drop_table('grade_history')
    with op.batch_alter_table('promotion_counter_reset', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_promotion_counter_reset_club_id'))

    op.drop_table('promotion_counter_reset')
    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_match_club_id'))

    op.drop_table('match')
    with op.batch_alter_table('blind_count', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blind_count_member_id'))
        batch_op.drop_index(batch_op.f('ix_blind_count_counted_from'))
        batch_op.drop_index(batch_op.f('ix_blind_count_club_id'))

    op.drop_table('blind_count')
    with op.batch_alter_table('activity_outside_record', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_outside_record_club_id'))

    op.drop_table('activity_outside_record')
    with op.batch_alter_table('today_participant', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_today_participant_club_id'))
        batch_op.drop_index('ix_today_participant_club_date_pid')

    op.drop_table('today_participant')
    with op.batch_alter_table('strength', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_strength_club_id'))

    op.drop_table('strength')
    with op.batch_alter_table('promotion_rule', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_promotion_rule_club_id'))
        batch_op.drop_index('ix_promotion_rule_club')

    op.drop_table('promotion_rule')
    with op.batch_alter_table('owner_audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_owner_audit_log_club_id'))

    op.drop_table('owner_audit_log')
    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_member_qr_token'))
        batch_op.drop_index(batch_op.f('ix_member_club_id'))

    op.drop_table('member')
    with op.batch_alter_table('match_card_state', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_match_card_state_club_id'))
        batch_op.drop_index('ix_match_card_state_club_date_card')

    op.drop_table('match_card_state')
    with op.batch_alter_table('default_card_count', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_default_card_count_club_id'))

    op.drop_table('default_card_count')
    with op.batch_alter_table('setting', schema=None) as batch_op:
        batch_op.drop_index('ix_setting_club_key')

    op.drop_table('setting')
    with op.batch_alter_table('handicap_rule', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_handicap_rule_club_id'))

    op.drop_table('handicap_rule')
    op.drop_table('club')
    # ### end Alembic commands ###
