"""add qr_token to member

Revision ID: 8ce430d43372
Revises: a468177be103
Create Date: 2025-08-16 17:37:14.373958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ce430d43372'
down_revision = 'a468177be103'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qr_token', sa.String(length=32), nullable=True))
        batch_op.create_index(batch_op.f('ix_member_qr_token'), ['qr_token'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_member_qr_token'))
        batch_op.drop_column('qr_token')

    # ### end Alembic commands ###
