"""empty message

Revision ID: e14b9ab628d7
Revises: 502ac87d94a1
Create Date: 2025-08-27 22:03:57.416096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e14b9ab628d7'
down_revision = '502ac87d94a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_outside_record', recreate="auto") as batch_op:
        batch_op.add_column(sa.Column('club_id', sa.String(length=32), nullable=True))
        batch_op.create_index('ix_activity_outside_record_club_id', ['club_id'], unique=False)
        batch_op.create_foreign_key(
            'fk_activity_outside_record_club_id_club', 'club', ['club_id'], ['id']
        )

    with op.batch_alter_table('handicap_rule', schema=None) as batch_op:
        batch_op.create_index('ix_handicap_rule_club', ['club_id'], unique=False)

    with op.batch_alter_table('initial_assessment_result', recreate="auto") as batch_op:
        batch_op.add_column(sa.Column('club_id', sa.String(length=32), nullable=True))
        batch_op.create_index('ix_initial_assessment_result_club_id', ['club_id'], unique=False)
        batch_op.create_foreign_key(
            'fk_initial_assessment_result_club_id_club', 'club', ['club_id'], ['id']
        )

    with op.batch_alter_table('match_card_state', schema=None) as batch_op:
        batch_op.alter_column('club_id',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)

    with op.batch_alter_table('match_memo', recreate="auto") as batch_op:
        batch_op.add_column(sa.Column('club_id', sa.String(length=32), nullable=True))
        batch_op.create_index('ix_match_memo_club_id', ['club_id'], unique=False)
        batch_op.create_foreign_key(
            'fk_match_memo_club_id_club', 'club', ['club_id'], ['id']
        )

    with op.batch_alter_table('promotion_rule', schema=None) as batch_op:
        batch_op.create_index('ix_promotion_rule_club', ['club_id'], unique=False)

    with op.batch_alter_table('setting', schema=None) as batch_op:
        batch_op.alter_column('club_id',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)

    with op.batch_alter_table('today_participant', schema=None) as batch_op:
        batch_op.alter_column('club_id',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('today_participant', schema=None) as batch_op:
        batch_op.alter_column('club_id',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)

    with op.batch_alter_table('setting', schema=None) as batch_op:
        batch_op.alter_column('club_id',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)

    with op.batch_alter_table('promotion_rule', schema=None) as batch_op:
        batch_op.drop_index('ix_promotion_rule_club')

    with op.batch_alter_table('match_memo', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_match_memo_club_id'))
        batch_op.drop_column('club_id')

    with op.batch_alter_table('match_card_state', schema=None) as batch_op:
        batch_op.alter_column('club_id',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)

    with op.batch_alter_table('initial_assessment_result', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_initial_assessment_result_club_id'))
        batch_op.drop_column('club_id')

    with op.batch_alter_table('handicap_rule', schema=None) as batch_op:
        batch_op.drop_index('ix_handicap_rule_club')

    with op.batch_alter_table('activity_outside_record', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_activity_outside_record_club_id'))
        batch_op.drop_column('club_id')

    # ### end Alembic commands ###
